# 1. Numpy
- c언어라서 속도가 빠르다.
- 고성능 수치계산을 위햇 제작
- Numerical Python
- 벡터 및 행렬 연산에 매우 편리한 기능 제공
- Pandas와 matplotlib과 더불어 데이터분석에 필수 라이브러리
- 기본적으로 array 단위로 데이터 처리
- 대표적인 자료형 : ndarray 객체

## 1.1 Numpy

In [ ]:
import numpy as np

## 1.2  Array 정의 및 사용

In [ ]:
# python의 list이용
a = [1,2,3,4,5]

In [ ]:
b = [1,2,3,4,5]
b

In [ ]:
arr1 = np.array(a)
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [ ]:
# array 형태(크기) 확인
arr1.shape

(5,)

In [ ]:
# array 자료형 확인
arr1.dtype

## 1.3 배열생성 : Numpy가 제공하는 함수를 이용한 단순 배열 생성
- zeros, ones
- zeros_like, ones_like
- empty
- arange
- linspace, logspace

In [ ]:
# 0인 배열 생성 : zeros(배열의 크기)
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
b = np.zeros(5, dtype="i") # int는i
b

array([0, 0, 0, 0, 0], dtype=int32)

- numpy 자료형, dtype의 접두사
- "i" : 정수형
- "u" : uint(unsign int), 부호가 없는 정수
- "f" : float
- "b" : 논리형(bool)
- "c" : 복소수(complex)
- "s" : 문자열(string)

In [ ]:
x= np.array([1,2,3], dtype='f')
x.dtype

dtype('float32')

In [ ]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
b = np.zeros((2,3), dtype='i')
b

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [ ]:
e = np.ones((2, 3, 4))
e

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
# 기본의 배열의 크기를 그대로 사용하여 배열 생성
## zeros_like
## ones_like
b

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [ ]:
f = np.ones_like(b)
f

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
g = np.empty((4,3))
g

array([[5.05164271e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
# range() : 순차리스트, 수열생성 함수
# range(5) : 0, 1, 2, 3
# range(1, 10) : 1, 9
# arange() : Numpy 버전의 range
np.arange(10) # 0 ~ n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## 1.4 전치행렬
- 행과 열을 바꾸는 기능
- T

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 1.5 배열의 크기 변형
- 배열의 크기 속성 : shape, 배열명.속성
- 배열의 크기 변경 : reshape

In [ ]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.shape

(12,)

In [ ]:
b = a.reshape(3, 4) # 3행으로 나누면 4는 안써도되긴한다. 그냥 -1하면 된다.
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [ ]:
# 다차원 배열을 1차원 배열로 생성하는 flatten(차원내림), ravel 메서드

In [ ]:
a = a.reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [ ]:
x.shape

(5,)

In [ ]:
x.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [ ]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
# 차원만 증가시키는 newaxis
x

array([0, 1, 2, 3, 4])

In [ ]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

# 2. Numpy 배열의 연산

In [84]:
x = np.arange(1,10001)
y = np.arange(10001,20001)

In [87]:
%%time
res = np.zeros_like(x)
for i in range(10000):
    res[i] = x[i] + y[i]

CPU times: user 6.17 ms, sys: 0 ns, total: 6.17 ms
Wall time: 6.96 ms


In [89]:
res[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [91]:
%%time
z  = x + y

CPU times: user 864 µs, sys: 0 ns, total: 864 µs
Wall time: 2.34 ms


In [93]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [98]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,3])
a == b

array([False,  True, False, False])

In [99]:
a >= b

array([False,  True,  True,  True])

In [101]:
np.all(a == b)

False

In [104]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [106]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [108]:
10 ** a

array([    1,    10,   100,  1000, 10000])

In [110]:
np.log(a+1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [112]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [119]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

## 브로드캐스팅(broadcasting)
- 서로 크기가 다른 배열의 사칙연산을 수행하는 기능
- 크기가 작은 배열이 자동적으로 크기가 큰 배열의 크기로 맞춰지는 기능

In [122]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [126]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [128]:
x + y

array([1, 2, 3, 4, 5])

In [132]:
y = np.arange(12).reshape(3,4)
y+1 # 이거 자체가 브로드캐스팅이다.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [134]:
z = np.ones_like(y)
z

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## 그룹함수 or 차원 축소 연산
- 최대/최소 : min, max, argmin, argmax # 그 값의 인덱스를 가져오는 arg(인수)
- 기초통계 : sum, mean, median, std, var
- 논리연산 : all, any

In [138]:
x = np.array([1,2,3,4])
x
np.sum(x)

10

In [139]:
x.sum()

10

In [141]:
x = np.array([1,3,2])
x

array([1, 3, 2])

In [142]:
np.min(x)

1

In [144]:
x.min()

1

In [146]:
x.argmin()

0

In [148]:
x.argmax()

1

In [149]:
x.mean()

2.0

In [151]:
np.mean(x)

2.0

In [153]:
np.median(x)

2.0

In [155]:
y = np.array([1,2,3,1])
y

array([1, 2, 3, 1])

In [157]:
np.median(y)

1.5

In [159]:
np.all([True, True, False])

False

In [161]:
np.any([True, True, False])

True

In [164]:
a = np.zeros((100,100), dtype='i')
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [165]:
np.any(a != 0)

False

In [167]:
np.all(a == a)

True

In [168]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,4])
c = np.array([6,4,4,5])

In [171]:
((a <= b) & (b <= c)).all()

True

- 축(axis) : axis=0(열), axis=1(행), default(axis=0)

In [173]:
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [175]:
x.sum()

6

In [179]:
x.sum(axis=1)

array([2, 4])

In [180]:
x.sum(axis=0)

array([3, 3])

## 정렬(sort)
- 2차원 이상일 경우에는 행이나 열을 각각 따로 정렬
- axis = 0이면 각 열을 기준으로 정렬, axis = 1이면 각 행을 기준으로 정렬
- 생략하면 axis = 0
- axis = -1가 주어지면 안쪽차원이 기준이 된다.

In [197]:
a = np.array([[4,3,5,7],
              [1,12,11,9],
              [2,15,1,14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [185]:
np.sort(a) # 여기서 생략하면 axis=1은 axis=-1과 동일하다.

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [187]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [189]:
np.sort(a, axis=-1)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [199]:
a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [202]:
# 정렬을 하지 않고 순서만 알고 싶다면 argsort 명령을 사용한다.
a = np.array([4,2,3,8])
b = np.argsort(a)
b

array([1, 2, 0, 3])

In [203]:
a[b]

array([2, 3, 4, 8])

In [205]:
np.sort(a)


array([2, 3, 4, 8])

## Fancy lndexing : 펜시인덱싱
- boolean 인덱싱을 이용하는 것
- 마스크 인덱싱
- 규칙이 일정하지 않지만 원하는 데이터를 추출하고자 할 때 사용한다.

In [207]:
names = np.array(['park','park','kim','joan','lee','park','hong','park'])
names

array(['park', 'park', 'kim', 'joan', 'lee', 'park', 'hong', 'park'],
      dtype='<U4')

In [208]:
names.shape

(8,)

In [211]:
# 정규분포 : np.random.randn(), 평균 0 표준편차 1인
# np.random.rand(): 0 ~ 1 사이의 난수 발생
data = np.random.randn(8,4)
data

array([[-0.24529635,  0.03773923,  0.90731457, -1.4150172 ],
       [ 0.08583596,  1.12890351, -0.65841709, -0.15583405],
       [ 0.36544944,  0.90334422,  1.05687054,  1.73105924],
       [ 0.33365094, -1.39940285,  0.53502244,  0.12698042],
       [ 1.70059599,  0.52055183,  0.22122777,  1.59974822],
       [-0.22070656, -0.56015165, -1.60987062,  0.37815062],
       [-0.31696465,  0.41919022, -1.38360486, -2.13322826],
       [ 0.11404892, -0.4723813 , -0.0998268 ,  0.23036204]])

In [213]:
data.shape

(8, 4)

In [217]:
index = (names == 'park')
data[index, :]

array([[-0.24529635,  0.03773923,  0.90731457, -1.4150172 ],
       [ 0.08583596,  1.12890351, -0.65841709, -0.15583405],
       [-0.22070656, -0.56015165, -1.60987062,  0.37815062],
       [ 0.11404892, -0.4723813 , -0.0998268 ,  0.23036204]])

In [220]:
# 요소가 'kim'인 행의 데이터만 추출
data[names == 'kim', :]

array([[0.36544944, 0.90334422, 1.05687054, 1.73105924]])

In [225]:
data[(names=='kim') | (names =='hong'),:]

array([[ 0.36544944,  0.90334422,  1.05687054,  1.73105924],
       [-0.31696465,  0.41919022, -1.38360486, -2.13322826]])

In [227]:
# 0번째 열의 값이 0보다 작은 행을 추출
data[:, 0] < 0

array([ True, False, False, False, False,  True,  True, False])

In [229]:
data[data[:, 0] < 0, :]

array([[-0.24529635,  0.03773923,  0.90731457, -1.4150172 ],
       [-0.22070656, -0.56015165, -1.60987062,  0.37815062],
       [-0.31696465,  0.41919022, -1.38360486, -2.13322826]])

In [234]:
# 0번째 열의 값이 0보다 작은 행의 2, 3번째 열의 값만 추출
data[data[:, 0] < 0, 2:4]

array([[ 0.90731457, -1.4150172 ],
       [-1.60987062,  0.37815062],
       [-1.38360486, -2.13322826]])

In [237]:
# 0번째 열의 값이 0보다 작은 행의 2,3 번째 열의 값을 0으로 치환
data[data[:, 0] < 0, 2:4] = 0
data

array([[-0.24529635,  0.03773923,  0.        ,  0.        ],
       [ 0.08583596,  1.12890351, -0.65841709, -0.15583405],
       [ 0.36544944,  0.90334422,  1.05687054,  1.73105924],
       [ 0.33365094, -1.39940285,  0.53502244,  0.12698042],
       [ 1.70059599,  0.52055183,  0.22122777,  1.59974822],
       [-0.22070656, -0.56015165,  0.        ,  0.        ],
       [-0.31696465,  0.41919022,  0.        ,  0.        ],
       [ 0.11404892, -0.4723813 , -0.0998268 ,  0.23036204]])

# 기술통계분석

In [238]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

## 데이터의 개수 : len

In [240]:
len(x)

26

## 평균:mean

In [242]:
np.mean(x)

4.8076923076923075

## 분산 : var

In [244]:
np.var(x)

115.23224852071006

In [246]:
# 비편향 분산
np.var(x,ddof=1)

119.84153846153846

## 표준 편차 : std

In [247]:
np.std(x)

10.734628476137871

## 최대값과 최소값 :  max, min

In [248]:
np.max(x)

23

In [250]:
np.min(x)

-24

## 중앙값 : median

In [251]:
np.median(x)

5.0

## 사분위수 : quantile, percentile

In [256]:
np.percentile(x,0) # 최소값


-24.0

In [258]:
np.percentile(x,25) # 최소값

0.0

In [257]:
np.percentile(x,100) # 최대값

23.0

# 난수(random number) : 랜덤값을 유지하고 싶은경우에 쓴다.

## 시드설정(seed) : 0과 같거나 큰 정수


In [274]:
np.random.seed(0)

In [283]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [275]:
np.random.rand(10)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [284]:
np.random.seed(0)

In [285]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [286]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [295]:
arr1 = np.random.random((3,3)) # 차원은 튜플로 묶는다.  균등분포, 0 ~ 1 실수를 사용한다.
arr2 = np.random.normal(2, 1, (3,2)) # 평균(2) 편차(1) 정규분포
arr3 = np.random.randn(2, 3) # 표준 정규분포, 평균(0), 편차(1)
arr4 = np.random.randint(0, 10, (2,2))

In [ ]:
print(arr1)
print(arr2)
print(arr3)
print(arr4)

## 데이터 샘플링(sampling), shuffle 명령과 같다
- np.choice(배열, size, replace, p)
- 배열 : arange(n)
- replace : 중복여부

In [300]:
np.random.choice(5, 5, replace=False)

array([0, 2, 3, 1, 4])

In [301]:
np.random.choice(5, 10)

array([3, 1, 1, 1, 3, 2, 2, 4, 3, 1])

In [302]:
np.random.choice(5, 10, p=[0.1,0,0.3,0.6,0])

array([3, 0, 2, 3, 2, 3, 0, 2, 0, 3])

In [303]:
# 0 ~ 1 사이의 균일분포
np.random.rand(10)

array([0.22392469, 0.34535168, 0.92808129, 0.7044144 , 0.03183893,
       0.16469416, 0.6214784 , 0.57722859, 0.23789282, 0.934214  ])

In [305]:
np.random.rand(3,5)

array([[0.31179588, 0.69634349, 0.37775184, 0.17960368, 0.02467873],
       [0.06724963, 0.67939277, 0.45369684, 0.53657921, 0.89667129],
       [0.99033895, 0.21689698, 0.6630782 , 0.26332238, 0.020651  ]])

In [314]:
# np.random.randint(low.high=None, size)
np.random.randint(10, size=10)

array([7, 8, 5, 0, 8, 5, 4, 7, 4, 1])

In [317]:
np.random.randint(10, 20, size=(3,5))

array([[16, 16, 17, 18, 18],
       [17, 10, 18, 16, 18],
       [19, 18, 13, 16, 11]])

## 정수 데이터 카운팅
- unique : 중복을 제거하고 중복되지 않는 값
- return_counts = True, 각 값의 갯수

In [318]:
np.unique([11,11,2,2,34,34])

array([ 2, 11, 34])

In [319]:
a = np.array(['a','b','b','c','a'])

In [321]:
np.unique(a)

array(['a', 'b', 'c'], dtype='<U1')

In [324]:
index, count = np.unique(a, return_counts=True)
index

array(['a', 'b', 'c'], dtype='<U1')

In [325]:
count

array([2, 2, 1])