# Data Analysis -2nd

In [ ]:
import numpy as np
# zeros, ones, full, eye
a = np.full((2,3), 5)
a
# eye : 정방행렬(행과 열의 수가 같은 거)
b = np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [ ]:
arr2d[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d[2] # 1개만 있으면 행을 나타냄

array([7, 8, 9])

In [ ]:
arr2d[2][0]

7

In [ ]:
arr2d[2,0]

7

In [ ]:
b = a
b

array([[5, 5, 5],
       [5, 5, 5]])

In [ ]:
a[0,0] = 100
b

array([[100,   5,   5],
       [  5,   5,   5]])

In [ ]:
# copy()
c = a.copy()
c

array([[100,   5,   5],
       [  5,   5,   5]])